# Generated by Django 4.1.7 on 2023-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='undefined', max_length=510),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(default='undefined', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('or', 'Never Worn, with Original Tags'), ('ne', 'Never Worn'), ('vg', 'Very Good Condition'), ('gd', 'Good Condition'), ('fr', 'Fair Condition')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.CharField(default='undefined', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='dimensions',
            field=models.CharField(default='undefined', max_length=255),
        ),
    ]
