# Generated by Django 4.1.7 on 2023-05-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('posts', '0003_post_address_post_color_post_condition_post_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='categories.category', to_field='name'),
        ),
    ]
